### ISSUE TITLE
sup_all_atm.pdb is not created

### ISSUE THREAD

**Issue by imerelli** [jianlin-cheng/PreMut#1]
Hi, 
while training the modeling, I always get this error (each time with a different pdb file).
As far as I understand, the TMP directory is created and the original pdb 
file is moved there, but then the *sup_all_atm.pdb is not created.
Can you help me?
Ivan

Epoch 0:   0%|                                                                                                                                                                | 0/203 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/opt/tools/deg/PreMut/src/train.py", line 48, in <module>
    training.fit(model_name='egnn')
  File "/opt/tools/deg/PreMut/src/train.py", line 43, in fit
    self.trainer.fit(model=lit_module,datamodule=datamodule)
  File "/opt/tools/deg/miniforge3/envs/PreMut/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 582, in fit
    call._call_and_handle_interrupt(
  File "/opt/tools/deg/miniforge3/envs/PreMut/lib/python3.10/site-packages/pytorch_lightning/trainer/call.py", line 38, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/opt/tools/deg/miniforge3/envs/PreMut/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 624, in _fit_impl
    self._run(model, ckpt_path=self.ckpt_path)
  File "/opt/tools/deg/miniforge3/envs/PreMut/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 1061, in _run
    results = self._run_stage()
  File "/opt/tools/deg/miniforge3/envs/PreMut/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 1140, in _run_stage
    self._run_train()
  File "/opt/tools/deg/miniforge3/envs/PreMut/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 1163, in _run_train
    self.fit_loop.run()
  File "/opt/tools/deg/miniforge3/envs/PreMut/lib/python3.10/site-packages/pytorch_lightning/loops/loop.py", line 199, in run
    self.advance(*args, **kwargs)
  File "/opt/tools/deg/miniforge3/envs/PreMut/lib/python3.10/site-packages/pytorch_lightning/loops/fit_loop.py", line 267, in advance
    self._outputs = self.epoch_loop.run(self._data_fetcher)
  File "/opt/tools/deg/miniforge3/envs/PreMut/lib/python3.10/site-packages/pytorch_lightning/loops/loop.py", line 199, in run
    self.advance(*args, **kwargs)
  File "/opt/tools/deg/miniforge3/envs/PreMut/lib/python3.10/site-packages/pytorch_lightning/loops/epoch/training_epoch_loop.py", line 214, in advance
    batch_output = self.batch_loop.run(kwargs)
  File "/opt/tools/deg/miniforge3/envs/PreMut/lib/python3.10/site-packages/pytorch_lightning/loops/loop.py", line 199, in run
    self.advance(*args, **kwargs)
  File "/opt/tools/deg/miniforge3/envs/PreMut/lib/python3.10/site-packages/pytorch_lightning/loops/batch/training_batch_loop.py", line 88, in advance
    outputs = self.optimizer_loop.run(optimizers, kwargs)
  File "/opt/tools/deg/miniforge3/envs/PreMut/lib/python3.10/site-packages/pytorch_lightning/loops/loop.py", line 199, in run
    self.advance(*args, **kwargs)
  File "/opt/tools/deg/miniforge3/envs/PreMut/lib/python3.10/site-packages/pytorch_lightning/loops/optimization/optimizer_loop.py", line 200, in advance
    result = self._run_optimization(kwargs, self._optimizers[self.optim_progress.optimizer_position])
  File "/opt/tools/deg/miniforge3/envs/PreMut/lib/python3.10/site-packages/pytorch_lightning/loops/optimization/optimizer_loop.py", line 247, in _run_optimization
    self._optimizer_step(optimizer, opt_idx, kwargs.get("batch_idx", 0), closure)
  File "/opt/tools/deg/miniforge3/envs/PreMut/lib/python3.10/site-packages/pytorch_lightning/loops/optimization/optimizer_loop.py", line 357, in _optimizer_step
    self.trainer._call_lightning_module_hook(
  File "/opt/tools/deg/miniforge3/envs/PreMut/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 1305, in _call_lightning_module_hook
    output = fn(*args, **kwargs)
  File "/opt/tools/deg/miniforge3/envs/PreMut/lib/python3.10/site-packages/pytorch_lightning/core/module.py", line 1661, in optimizer_step
    optimizer.step(closure=optimizer_closure)
  File "/opt/tools/deg/miniforge3/envs/PreMut/lib/python3.10/site-packages/pytorch_lightning/core/optimizer.py", line 169, in step
    step_output = self._strategy.optimizer_step(self._optimizer, self._optimizer_idx, closure, **kwargs)
  File "/opt/tools/deg/miniforge3/envs/PreMut/lib/python3.10/site-packages/pytorch_lightning/strategies/strategy.py", line 234, in optimizer_step
    return self.precision_plugin.optimizer_step(
  File "/opt/tools/deg/miniforge3/envs/PreMut/lib/python3.10/site-packages/pytorch_lightning/plugins/precision/precision_plugin.py", line 121, in optimizer_step
    return optimizer.step(closure=closure, **kwargs)
  File "/opt/tools/deg/miniforge3/envs/PreMut/lib/python3.10/site-packages/torch/optim/optimizer.py", line 113, in wrapper
    return func(*args, **kwargs)
  File "/opt/tools/deg/miniforge3/envs/PreMut/lib/python3.10/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/opt/tools/deg/miniforge3/envs/PreMut/lib/python3.10/site-packages/torch/optim/adam.py", line 118, in step
    loss = closure()
  File "/opt/tools/deg/miniforge3/envs/PreMut/lib/python3.10/site-packages/pytorch_lightning/plugins/precision/precision_plugin.py", line 107, in _wrap_closure
    closure_result = closure()
  File "/opt/tools/deg/miniforge3/envs/PreMut/lib/python3.10/site-packages/pytorch_lightning/loops/optimization/optimizer_loop.py", line 147, in __call__
    self._result = self.closure(*args, **kwargs)
  File "/opt/tools/deg/miniforge3/envs/PreMut/lib/python3.10/site-packages/pytorch_lightning/loops/optimization/optimizer_loop.py", line 133, in closure
    step_output = self._step_fn()
  File "/opt/tools/deg/miniforge3/envs/PreMut/lib/python3.10/site-packages/pytorch_lightning/loops/optimization/optimizer_loop.py", line 406, in _training_step
    training_step_output = self.trainer._call_strategy_hook("training_step", *kwargs.values())
  File "/opt/tools/deg/miniforge3/envs/PreMut/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 1443, in _call_strategy_hook
    output = fn(*args, **kwargs)
  File "/opt/tools/deg/miniforge3/envs/PreMut/lib/python3.10/site-packages/pytorch_lightning/strategies/strategy.py", line 378, in training_step
    return self.model.training_step(*args, **kwargs)
  File "/opt/tools/deg/PreMut/src/LitModule.py", line 259, in training_step
    return self.step(batch,batch_idx,state='train')
  File "/opt/tools/deg/PreMut/src/LitModule.py", line 199, in step
    graph, label, info = self.prepare_graph(batch=batch,state=state)
  File "/opt/tools/deg/PreMut/src/LitModule.py", line 134, in prepare_graph
    graph, label_coords = pdb_reader.pdb_to_graph()
  File "/opt/tools/deg/PreMut/src/PDB_all_atom.py", line 529, in pdb_to_graph
    node_coords, label_coords = self.get_xyz()
  File "/opt/tools/deg/PreMut/src/PDB_all_atom.py", line 257, in get_xyz
    wild_df, mutant_df = self.do_TMalign(wild_ppdb=wild_ppdb,mutant_ppdb=mutant_ppdb)
  File "/opt/tools/deg/PreMut/src/PDB_all_atom.py", line 242, in do_TMalign
    pdb = PandasPdb().read_pdb('TMP/{0}_{1}.sup_all_atm.pdb'.format(self.wild_pdb,self.mutant_pdb))
  File "/opt/tools/deg/miniforge3/envs/PreMut/lib/python3.10/site-packages/biopandas/pdb/pandas_pdb.py", line 94, in read_pdb
    self.pdb_path, self.pdb_text = self._read_pdb(path=path)
  File "/opt/tools/deg/miniforge3/envs/PreMut/lib/python3.10/site-packages/biopandas/pdb/pandas_pdb.py", line 316, in _read_pdb
    with openf(path, r_mode) as f:
FileNotFoundError: [Errno 2] No such file or directory: 'TMP/1ire_7w8m.sup_all_atm.pdb'

**Comment by sajidmahmud** [comment]
Hello,
Could you check if you have installed TMalign? It is required for the training portion.
